import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  en: {
    translation: {
      nav: {
        dashboard: 'Dashboard', products: 'Products', delivery: 'Delivery', newOrder: 'New Order', sales: 'Sales', zones: 'Delivery Zones', settings: 'Shop Settings', logout: 'Logout'
      },
      dashboard: { welcome: 'Welcome back', todaySales: "Today's Sales", thisMonth: 'This Month', totalOrders: 'Total Orders', pendingPayments: 'Pending Payments', recentOrders: 'Recent Orders', topProducts: 'Top Products', viewAll: 'View All', noOrders: 'No orders yet', lowStock: 'Low Stock Alert', pendingDeliveries: 'orders in transit' },
      products: { title: 'Product Catalog', subtitle: 'Manage product codes, names, aliases, variants, stock, and prices for parsing and invoices.', addProduct: 'Add Product', importUrl: 'Import from URL', syncAI: 'Sync AI Search', exportInventory: 'Export Inventory', productCode: 'Product Code', productName: 'Product Name', banglaName: 'Bangla Name', sellingPrice: 'Selling Price', costPrice: 'Cost Price', stock: 'Stock', variants: 'Variants', tags: 'Search Tags', inStock: 'In Stock', lowStock: 'Low Stock', outOfStock: 'Out of Stock', noProducts: 'No products yet. Add your first product!', profitPerUnit: 'Profit per unit', save: 'Save Product', cancel: 'Cancel', deleteConfirm: 'Are you sure you want to delete this product?', aiSearchActive: 'AI Search Active', aiSearchInactive: 'AI Search Not Synced' },
      order: { title: 'New Order', subtitle: 'Choose how the customer sent the message, then paste the chat.', structuredChat: 'Structured Chat', unstructuredChat: 'Unstructured Chat', structuredDesc: 'Customer used order format with labels', unstructuredDesc: 'Customer sent a normal conversation', parseChat: 'Parse Chat', parseWithAI: 'Parse with AI', reviewOrder: 'Review Order', customerInfo: 'Customer Info', customerName: 'Customer Name', phone: 'Phone Number', fullAddress: 'Full Address', detectedZone: 'Detected Zone', zoneOverride: 'Zone Override', deliveryCharge: 'Delivery Charge', products: 'Products', product: 'Product', qty: 'Qty', unitPrice: 'Unit Price', total: 'Total', addProduct: 'Add Product Row', orderSummary: 'Order Summary', subtotal: 'Subtotal', discount: 'Discount', grandTotal: 'Grand Total', payment: 'Payment', fullOnline: 'Full Payment Online', deliveryOnline: 'Delivery Charge Online Only', fullCOD: 'Full COD', paymentMethod: 'Payment Method', transactionId: 'Transaction ID', notes: 'Special Instructions', generateInvoice: 'Generate Invoice', backToChat: 'Back to Chat', saveOrder: 'Save & Record Sale', downloadPDF: 'Download PDF', downloadImage: 'Download Image', print: 'Print Invoice', copyTemplate: 'Copy Order Format', returningCustomer: 'Returning Customer', previousOrders: 'previous orders', totalSpent: 'Total spent', stockWarning: 'only in stock but ordered', codeMatch: 'Code Match', aiMatch: 'AI Match', manual: 'Manual' },
      sales: { title: 'Sales History', newOrder: 'New Order', exportExcel: 'Export Excel', search: 'Search orders...', filterStatus: 'Payment Status', filterMethod: 'Payment Method', filterType: 'Payment Type', filterDate: 'Date Range', clearFilters: 'Clear Filters', orderNo: 'Order #', date: 'Date', customer: 'Customer', zone: 'Zone', items: 'Items', total: 'Total', method: 'Method', status: 'Status', actions: 'Actions', view: 'View', invoice: 'Invoice', delete: 'Delete', markPaid: 'Mark as Paid', noSales: 'No sales recorded yet', showing: 'Showing', of: 'of', orders: 'orders', paid: 'Paid', unpaid: 'Unpaid', partial: 'Partial' },
      delivery: { title: 'Delivery Inventory', subtitle: 'Orders currently in transit', exportExcel: 'Export Excel', pending: 'Pending', delivered: 'Delivered', notDelivered: 'Not Delivered', returned: 'Returned', cancelled: 'Cancelled', markDelivered: 'Mark as Delivered', markNotDelivered: 'Mark as Not Delivered', markReturned: 'Mark as Returned', markCancelled: 'Mark as Cancelled', noDeliveries: 'No orders in delivery inventory yet', restocked: 'Items returned to inventory' },
      zones: { title: 'Delivery Zones', subtitle: 'Configure home city, specific city, and outside base city delivery charges.', addZone: 'Add Zone', quickSetup: 'Quick Setup', area: 'Area Name', banglaArea: 'Bangla Name', charge: 'Delivery Charge', keywords: 'Keywords', homeCity: 'Home City', outsideCity: 'Outside Base City', noZones: 'No delivery zones yet', deleteConfirm: 'Delete this zone?' },
      settings: { title: 'Shop Settings', subtitle: 'Keep seller profile, payment numbers, and base district ready for invoices and delivery automation.', shopName: 'Shop Name', ownerName: 'Owner Name', phone: 'Phone Number', baseCity: 'Base City', bkash: 'bKash Number', nagad: 'Nagad Number', email: 'Email', address: 'Shop Address', logo: 'Shop Logo', uploadLogo: 'Upload Logo', removeLogo: 'Remove Logo', saveChanges: 'Save Changes', shopUrl: 'Shop URL' },
      common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', add: 'Add', search: 'Search', loading: 'Loading...', success: 'Success', error: 'Error', confirm: 'Confirm', close: 'Close', yes: 'Yes', no: 'No', taka: '৳', pieces: 'pcs', back: 'Back', next: 'Next', submit: 'Submit', export: 'Export', import: 'Import', sync: 'Sync', refresh: 'Refresh', language: 'Language', theme: 'Theme', darkMode: 'Dark Mode', lightMode: 'Light Mode' },
      auth: { login: 'Login', register: 'Create Account', email: 'Email Address', password: 'Password', confirmPassword: 'Confirm Password', fullName: 'Full Name', loginBtn: 'Login', registerBtn: 'Create Account', noAccount: 'New seller? Create Account', hasAccount: 'Already have an account? Login', step1: 'Step 1 of 2', step2: 'Step 2 of 2', shopSetup: 'Shop Setup', completeSetup: 'Complete Setup', next: 'Next', welcome: 'Welcome back', tagline: 'AI-powered POS for Bangladeshi online sellers', rememberMe: 'Remember me' }
    }
  },
  bn: {
    translation: {
      nav: { dashboard: 'ড্যাশবোর্ড', products: 'পণ্যসমূহ', delivery: 'ডেলিভারি', newOrder: 'নতুন অর্ডার', sales: 'বিক্রয়', zones: 'ডেলিভারি জোন', settings: 'শপ সেটিংস', logout: 'লগআউট' },
      dashboard: { welcome: 'স্বাগতম', todaySales: 'আজকের বিক্রয়', thisMonth: 'এই মাসে', totalOrders: 'মোট অর্ডার', pendingPayments: 'বাকি পেমেন্ট', recentOrders: 'সাম্প্রতিক অর্ডার', topProducts: 'সেরা পণ্য', viewAll: 'সব দেখুন', noOrders: 'এখনো কোনো অর্ডার নেই', lowStock: 'স্বল্প স্টক সতর্কতা', pendingDeliveries: 'অর্ডার ডেলিভারিতে আছে' },
      products: { title: 'পণ্য তালিকা', subtitle: 'পণ্য কোড, নাম, ভেরিয়েন্ট, স্টক ও দাম ম্যানেজ করুন।', addProduct: 'পণ্য যোগ করুন', importUrl: 'URL থেকে আমদানি', syncAI: 'AI সার্চ সিঙ্ক করুন', exportInventory: 'ইনভেন্টরি ডাউনলোড', productCode: 'পণ্য কোড', productName: 'পণ্যের নাম', banglaName: 'বাংলা নাম', sellingPrice: 'বিক্রয় মূল্য', costPrice: 'ক্রয় মূল্য', stock: 'স্টক', variants: 'ভেরিয়েন্ট', tags: 'সার্চ ট্যাগ', inStock: 'স্টক আছে', lowStock: 'স্বল্প স্টক', outOfStock: 'স্টক নেই', noProducts: 'এখনো কোনো পণ্য নেই। প্রথম পণ্য যোগ করুন!', profitPerUnit: 'প্রতি পিস লাভ', save: 'পণ্য সেভ করুন', cancel: 'বাতিল', deleteConfirm: 'এই পণ্যটি মুছে ফেলবেন?', aiSearchActive: 'AI সার্চ চালু', aiSearchInactive: 'AI সার্চ সিঙ্ক করা হয়নি' },
      order: { title: 'নতুন অর্ডার', subtitle: 'কাস্টমার কীভাবে মেসেজ করেছে তা বেছে নিয়ে চ্যাট পেস্ট করুন।', structuredChat: 'স্ট্রাকচার্ড চ্যাট', unstructuredChat: 'আনস্ট্রাকচার্ড চ্যাট', structuredDesc: 'কাস্টমার ফরম্যাট মেনে মেসেজ করেছে', unstructuredDesc: 'কাস্টমার সাধারণ কথোপকথনে মেসেজ করেছে', parseChat: 'চ্যাট পার্স করুন', parseWithAI: 'AI দিয়ে পার্স করুন', reviewOrder: 'অর্ডার রিভিউ করুন', customerInfo: 'কাস্টমার তথ্য', customerName: 'কাস্টমারের নাম', phone: 'ফোন নম্বর', fullAddress: 'সম্পূর্ণ ঠিকানা', detectedZone: 'শনাক্ত জোন', zoneOverride: 'জোন পরিবর্তন', deliveryCharge: 'ডেলিভারি চার্জ', products: 'পণ্যসমূহ', product: 'পণ্য', qty: 'পরিমাণ', unitPrice: 'একক মূল্য', total: 'মোট', addProduct: 'পণ্য যোগ করুন', orderSummary: 'অর্ডার সারসংক্ষেপ', subtotal: 'সাবটোটাল', discount: 'ছাড়', grandTotal: 'সর্বমোট', payment: 'পেমেন্ট', fullOnline: 'সম্পূর্ণ অনলাইনে', deliveryOnline: 'শুধু ডেলিভারি চার্জ অনলাইনে', fullCOD: 'সম্পূর্ণ ক্যাশ অন ডেলিভারি', paymentMethod: 'পেমেন্ট পদ্ধতি', transactionId: 'ট্রানজেকশন আইডি', notes: 'বিশেষ নির্দেশনা', generateInvoice: 'ইনভয়েস তৈরি করুন', backToChat: 'চ্যাটে ফিরে যান', saveOrder: 'অর্ডার সেভ করুন', downloadPDF: 'PDF ডাউনলোড', downloadImage: 'ছবি ডাউনলোড', print: 'প্রিন্ট করুন', copyTemplate: 'অর্ডার ফরম্যাট কপি করুন', returningCustomer: 'পুরোনো কাস্টমার', previousOrders: 'টি আগের অর্ডার', totalSpent: 'মোট খরচ', stockWarning: 'টি স্টক আছে কিন্তু অর্ডার করা হয়েছে', codeMatch: 'কোড ম্যাচ', aiMatch: 'AI ম্যাচ', manual: 'ম্যানুয়াল' },
      sales: { title: 'বিক্রয় ইতিহাস', newOrder: 'নতুন অর্ডার', exportExcel: 'এক্সেল ডাউনলোড', search: 'অর্ডার খুঁজুন...', filterStatus: 'পেমেন্ট স্ট্যাটাস', filterMethod: 'পেমেন্ট পদ্ধতি', filterType: 'পেমেন্ট ধরন', filterDate: 'তারিখ', clearFilters: 'ফিল্টার মুছুন', orderNo: 'অর্ডার নং', date: 'তারিখ', customer: 'কাস্টমার', zone: 'জোন', items: 'আইটেম', total: 'মোট', method: 'পদ্ধতি', status: 'স্ট্যাটাস', actions: 'অ্যাকশন', view: 'দেখুন', invoice: 'ইনভয়েস', delete: 'মুছুন', markPaid: 'পেইড করুন', noSales: 'এখনো কোনো বিক্রয় নেই', showing: 'দেখাচ্ছে', of: 'এর মধ্যে', orders: 'অর্ডার', paid: 'পেইড', unpaid: 'বাকি', partial: 'আংশিক' },
      delivery: { title: 'ডেলিভারি ইনভেন্টরি', subtitle: 'বর্তমানে ট্রানজিটে থাকা অর্ডার', exportExcel: 'এক্সেল ডাউনলোড', pending: 'অপেক্ষমান', delivered: 'ডেলিভারি হয়েছে', notDelivered: 'ডেলিভারি হয়নি', returned: 'ফেরত এসেছে', cancelled: 'বাতিল', markDelivered: 'ডেলিভারি হয়েছে', markNotDelivered: 'ডেলিভারি হয়নি', markReturned: 'ফেরত এসেছে', markCancelled: 'বাতিল করুন', noDeliveries: 'ডেলিভারি ইনভেন্টরি খালি', restocked: 'পণ্য ইনভেন্টরিতে ফেরত গেছে' },
      zones: { title: 'ডেলিভারি জোন', subtitle: 'হোম সিটি, নির্দিষ্ট সিটি ও বাইরের এলাকার চার্জ সেট করুন।', addZone: 'জোন যোগ করুন', quickSetup: 'দ্রুত সেটআপ', area: 'এলাকার নাম', banglaArea: 'বাংলা নাম', charge: 'ডেলিভারি চার্জ', keywords: 'কীওয়ার্ড', homeCity: 'হোম সিটি', outsideCity: 'বেস সিটির বাইরে', noZones: 'এখনো কোনো জোন নেই', deleteConfirm: 'এই জোনটি মুছবেন?' },
      settings: { title: 'শপ সেটিংস', subtitle: 'সেলার প্রোফাইল, পেমেন্ট নম্বর ও বেস জেলা আপডেট রাখুন।', shopName: 'শপের নাম', ownerName: 'মালিকের নাম', phone: 'ফোন নম্বর', baseCity: 'বেস সিটি', bkash: 'বিকাশ নম্বর', nagad: 'নগদ নম্বর', email: 'ইমেইল', address: 'শপের ঠিকানা', logo: 'শপ লোগো', uploadLogo: 'লোগো আপলোড করুন', removeLogo: 'লোগো মুছুন', saveChanges: 'পরিবর্তন সেভ করুন', shopUrl: 'শপ URL' },
      common: { save: 'সেভ করুন', cancel: 'বাতিল', delete: 'মুছুন', edit: 'সম্পাদনা', add: 'যোগ করুন', search: 'খুঁজুন', loading: 'লোড হচ্ছে...', success: 'সফল', error: 'ত্রুটি', confirm: 'নিশ্চিত করুন', close: 'বন্ধ করুন', yes: 'হ্যাঁ', no: 'না', taka: '৳', pieces: 'পিস', back: 'পিছনে', next: 'পরবর্তী', submit: 'জমা দিন', export: 'ডাউনলোড', import: 'আমদানি', sync: 'সিঙ্ক', refresh: 'রিফ্রেশ', language: 'ভাষা', theme: 'থিম', darkMode: 'ডার্ক মোড', lightMode: 'লাইট মোড' },
      auth: { login: 'লগইন', register: 'অ্যাকাউন্ট তৈরি করুন', email: 'ইমেইল ঠিকানা', password: 'পাসওয়ার্ড', confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন', fullName: 'পুরো নাম', loginBtn: 'লগইন করুন', registerBtn: 'অ্যাকাউন্ট তৈরি করুন', noAccount: 'নতুন সেলার? অ্যাকাউন্ট তৈরি করুন', hasAccount: 'অ্যাকাউন্ট আছে? লগইন করুন', step1: 'ধাপ ১ এর ২', step2: 'ধাপ ২ এর ২', shopSetup: 'শপ সেটআপ', completeSetup: 'সেটআপ সম্পন্ন করুন', next: 'পরবর্তী', welcome: 'স্বাগতম', tagline: 'বাংলাদেশি অনলাইন সেলারদের জন্য AI POS', rememberMe: 'মনে রাখুন' }
    }
  }
}

i18n.use(initReactI18next).init({ resources, lng: localStorage.getItem('sellerbot-language') || 'en', fallbackLng: 'en', interpolation: { escapeValue: false } })

export default i18n
